name: Android CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache android ndk and extra
      uses: actions/cache@v2
      with:
        path: |
          $ANDROID_HOME/ndk/16.1.4479499/
          extra/boringssl/
          extra/soundtouch/
          extra/ffmpeg/
          extra/libyuv/
        key: ${{ runner.os }}-ndk16-extra

    - name: Setup ndk
      run: |
        yes 2>/dev/null | sudo $ANDROID_HOME/tools/bin/sdkmanager --update
        yes 2>/dev/null | sudo $ANDROID_HOME/tools/bin/sdkmanager --licenses > /dev/null
        yes 2>/dev/null | sudo $ANDROID_HOME/tools/bin/sdkmanager --install "ndk;16.1.4479499"
        yes 2>/dev/null | sudo $ANDROID_HOME/tools/bin/sdkmanager --install "cmake;3.10.2.4988404"
        yes 2>/dev/null | sudo $ANDROID_HOME/tools/bin/sdkmanager --licenses > /dev/null
        export ANDROID_NDK=$ANDROID_HOME/ndk/16.1.4479499/


    - name: Init extra for android
      run: |
        export ANDROID_NDK=$ANDROID_HOME/ndk/16.1.4479499/
        bash init-android.sh
        bash init/init-android-boringssl.sh
        bash init/init-android-libsrt.sh

    - name: Build ssl and ffmpeg
      run: |
        cd android/contrib
        export ANDROID_NDK=$ANDROID_HOME/ndk/16.1.4479499/
        bash compile-boringssl.sh all
        bash compile-libsrt.sh all
        wget --no-check-certificate https://raw.githubusercontent.com/FFmpeg/gas-preprocessor/master/gas-preprocessor.pl
        chmod +x gas-preprocessor.pl && sudo mv gas-preprocessor.pl /usr/local/bin/
        bash compile-ffmpeg.sh all

    - name: Build with Gradle
      run: |
        export ANDROID_NDK=$ANDROID_HOME/ndk/16.1.4479499/
        cd android/ijkplayer && ./gradlew build && ./gradlew assembleRelease

    - name: Upload apk
      uses: actions/upload-artifact@v2
      with:
        name: ijkdemo-release.apk
        path: android/ijkplayer/ijkplayer-example/build/outputs/apk/release/ijkplayer-example-release.apk